name: a3fe
channels:

  - conda-forge
  - "openbiosim/label/dev"

dependencies:
    # Base depends
  - arviz
  - pandas
  - python>=3.9
  - pip
  - numpy
  - matplotlib
  - scipy
  - ipython
  - pymbar<4
  - ambertools
  - biosimspace>2023.4
  - pydantic
  - loguru
